
POST http://localhost:8000/api/auth/register
Content-Type: application/json

 {
     "username": "trung",
     "password": "123456789aB",
     "last_name": "Trung",
     "first_name": "Tran",
     "email": "trung@gmail.com",
     "phone": "123"
 }

###

POST http://localhost:8000/api/auth/login
Content-Type: application/json

 {
     "username": "trung",
     "password": "123456789aB"
 }

###

GET http://localhost:8000/api/home
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InVzZXJuYW1lIjoidHJ1bmciLCJmaXJzdF9uYW1lIjoiVHJhbiIsImxhc3RfbmFtZSI6IlRydW5nIn0sImlhdCI6MTYzMjU0OTgyMSwiZXhwIjoxNjMyNTU3MDIxfQ.9e8n8qRzreKEnhyAx47ZjjrpZctq6_qdas6aziL2jYk
